Adds Rationale and Alternatives, Unresolved Questions, Success Metrics sections
helium/HIP pull request #510
Opened 2022-12-15 22:02 UTC by meowshka

2022-12-15 22:53 UTC, vincenzospaghetti requested changes
This looks great. I left one comment on the deployment impact. After that it looks good to merge.

2022-12-15 22:53 UTC, vincenzospaghetti commented on 0074-mobile-poc-modeled-coverage-rewards.md
> +# Stakeholders & Deployment Impact
Can we expand this a bit? Deployment impact should include what changes folks will see.
 For example:
- They will see changes to the Mobile explorer (new)
- They will see changes to rewards. You will need to update your firmware (if that's what they do) to comply with the change.
- They will see changes to how indoor coverage is rewarded 
- They will continue to see HIPs that support the mobile POC roadmap - which you can find here. 

Altogether, need to be explicit with folks about deployment impacts (what is changing).

2022-12-16 17:42 UTC, meowshka commented
@vincenzospaghetti changes addessed.

2022-12-16 17:47 UTC, zer0tweets approved these changes

2022-12-16 18:38 UTC, ke6jjj approved these changes

2022-12-16 19:17 UTC, merged