Update 0082-helium-mobile-service-provider.md
helium/HIP pull request #655
Opened 2023-05-14 22:01 UTC by zer0tweets

Updating HIP with the following: 

- Grace period changed to 6 months from one year 
- If opt-out not implemented past 6 months, reward cap goes away until implementation is complete 
- Reward cap is adjusted every year based to be 1 standard deviation away from average subscriber (per KeithR proposal)

2023-05-14 22:06 UTC, abhay requested changes

2023-05-14 22:06 UTC, abhay commented on 0082-helium-mobile-service-provider.md
> +Additionally, we propose a 6 calendar month grace period to allow for unrewarded traffic over 30GB per Subscriber on the Hotspots. Nova Labs will implement an option to opt-out of unrewarded data tra
```suggestion
Additionally, we propose a 6 calendar month grace period to allow for unrewarded traffic over 30GB per Subscriber on the Hotspots. Nova Labs will implement an option to opt-out of unrewarded data traffic in a Cloud Dashboard or similar tool no later than the expiration of the grace period. 6 month countdown will start on the day this HIP is approved.  
```

2023-05-15 18:51 UTC, vincenzospaghetti commented
@abhay - your change was accepted! Need your final review before we're able to merge.

2023-05-15 18:52 UTC, abhay approved these changes

2023-05-15 18:52 UTC, abhay commented
> @abhay - your change was accepted! Need your final review before we're able to merge.

typo recommendation. merging.

2023-05-15 18:52 UTC, merged