Premine error - updates
helium/HIP pull request #760
Opened 2023-08-16 06:16 UTC by leogaggl

1) Change the number of affected hotspots (as per checks done by @gradoj )
2) Clarify the wording on Helium Foundation funding as suggested by @capjbadger007
3) Minor spelling changes

2023-08-16 15:44 UTC, abhay commented on 0092-premine-error-correction.md
> +2. Each qualifying Hotspot will be awarded 5,798.755355 (2,500,000,000 available IOT tokens / 431,127 rewarded Hotspots at migration) IOT tokens out of the multi-sig wallet and transferred to the wal
added a specific team who is responsible to make this actually happen on chain.

2023-08-16 15:45 UTC, abhay requested changes
one minor edit and this lgtm.

2023-08-17 05:40 UTC, leogaggl commented on 0092-premine-error-correction.md
> +2. Each qualifying Hotspot will be awarded 5,798.755355 (2,500,000,000 available IOT tokens / 431,127 rewarded Hotspots at migration) IOT tokens out of the multi-sig wallet and transferred to the wal
Thanks for those changes. 

Makes sense from my point of view!

2023-08-17 13:20 UTC, abhay approved these changes

2023-08-17 13:21 UTC, abhay commented
Merging edits on behalf of author.

2023-08-17 13:21 UTC, merged